Regression bug fix: Birt reports' schedulation fails on certain environments because of a jar conflict: commons-codec-1.9.jar and org.apache.commons.codec-1.3.jar. Error was java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.decodeBase64(Ljava/lang/String;). We exclude org.apache.commons.codec-1.3.jar from dependencies list and keep only commons-codec-1.9.jar